version: "2"

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - errorlint

  settings:
    errcheck:
      # To disable the errcheck built-in exclude list.
      # See `-excludeonly` option in https://github.com/kisielk/errcheck#excluding-functions for details.
      # Default: false
      disable-default-exclusions: true

    staticcheck:
      checks:
        - all
        - -SA1019

formatters:
  enable:
    - gofmt
    - gofumpt