name: Call Release Doc

on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
      submit:
        required: true
        type: string
    outputs:
      artifact:
        description: "name of artifact"
        value: website_package_artifact
  # --- call by manual
  workflow_dispatch:
    inputs:
      ref:
        description: 'branch, tag, sha'
        required: true
        default: main


permissions: write-all

env:
  MERGE_BRANCH: github_pages
  SRC_DIRECTORY: 'docs'
  DEST_DIRECTORY: 'docs'
  PR_LABEL: pr/release/robot_update_githubpage
  PR_REVIWER: weizhoublue

jobs:
  get_ref:
    runs-on: ubuntu-latest
    outputs:
      ref: ${{ env.REF }}
      submit: ${{ env.SUBMIT }}
      docs_tag: ${{ env.DOCS_TAG }}
      set_latest: ${{ env.SET_LATEST }}
      skip_all_job: ${{ env.SKIP_ALL_JOB }}
    steps:
      - name: Get Ref
        id: get_ref
        run: |
          pwd
          ls
          if ${{ github.event_name == 'workflow_dispatch' }}; then
              echo "call by workflow_dispatch"
              echo "REF=${{ github.event.inputs.ref }}" >> $GITHUB_ENV
              echo "SUBMIT=true" >> $GITHUB_ENV
          elif ${{ inputs.ref != '' }}; then
              echo "call by workflow_call"
              echo "REF=${{ inputs.ref }}" >> $GITHUB_ENV
              echo "SUBMIT=${{ inputs.submit }}" >> $GITHUB_ENV
          else
              echo "unexpected event: ${{ github.event_name }}"
              exit 1
          fi

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.REF }}

      - name: Extract Version
        id: extract
        run: |
          if ! grep -E "^[[:space:]]*v[0-9]+.[0-9]+.[0-9]+[[:space:]]*$" VERSION &>/dev/null ; then
            echo "Skip, your version should be in vx.y.z format, not something else like v0.6.0-rc1."
            echo "SKIP_ALL_JOB=true" >> $GITHUB_ENV
            exit 0
          fi
          # for example v0.6.1, the build's documentation version is v0.6
          docVersion=` cat VERSION  | tr -d ' ' | tr -d '\n' | grep -Eo "v[0-9]+\.[0-9]+" `
          if [ -n "${docVersion}" ]; then
              echo "the version intercepted from the branch is: ${docVersion}"
          else
              echo "error, failed to get version, is your version in v0.6.* format?" && exit 1
          fi
          git checkout -f ${{ env.MERGE_BRANCH }}
          echo "Switch to the branch:${{ env.MERGE_BRANCH }} where the document is located"
          ls
          if [ -e "docs/${docVersion}" ]; then
              echo "doc version:${docVersion} already exists, just update it."
              echo "SET_LATEST=false" >> $GITHUB_ENV
          else
              echo "The doc version:${docVersion} does not exist yet, while generating the doc and set it to latest"
              echo "SET_LATEST=true" >> $GITHUB_ENV
          fi
          echo "the doc version is: ${docVersion}"
          echo "DOCS_TAG=${docVersion}" >> $GITHUB_ENV

  build_doc:
    runs-on: ubuntu-latest
    needs: get_ref
    if: ${{ needs.get_ref.outputs.skip_all_job != 'true' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ needs.get_ref.outputs.ref }}

      - name: build doc
        run: |
          pip install mkdocs==1.5.2 mike==1.1.2 mkdocs-material==8.5.11
          git config user.email "robot@example.com"
          git config user.name "robot"
          cp ./docs/mkdocs.yml ./
          if ${{ needs.get_ref.outputs.set_latest == 'true' }} ;then
              echo "generate doc version:${{ needs.get_ref.outputs.docs_tag }} and set to latest."
              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} --update-aliases ${{ needs.get_ref.outputs.docs_tag }} latest
              mike set-default --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} latest
          else
              echo "the version:${{ needs.get_ref.outputs.docs_tag }} of the doc does not need to be set to the latest."
              mike deploy --rebase --prefix ${{ env.DEST_DIRECTORY }} -b ${{ env.MERGE_BRANCH }} ${{ needs.get_ref.outputs.docs_tag }}
          fi
          rm -rf ./site
          rm -rf ./mkdocs.yml
          git checkout -f  ${{ env.MERGE_BRANCH }}
          echo "Push a doc version: ${{ needs.get_ref.outputs.docs_tag }} from branch: ${{ needs.get_ref.outputs.ref }}, update it to latest: ${{ needs.get_ref.outputs.set_latest }} "

      # Allow auto-merge on general
      - name: Create Pull Request
        id: create_pr
        if: ${{ needs.get_ref.outputs.submit == 'true' }}
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          title: "robot update website from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
          commit-message: "robot update website from ${{ needs.prepare_doc.outputs.ref }} to branch ${{ env.MERGE_BRANCH }} "
          branch-suffix: timestamp
          branch: robot/update_doc
          delete-branch: true
          base: ${{ env.MERGE_BRANCH }}
          signoff: true
          token: ${{ secrets.WELAN_PAT }}
          labels: ${{ env.PR_LABEL }}
          reviewers: ${{ env.PR_REVIWER }}
